### ISSUE TITLE
Questions of the future development

### ISSUE THREAD

**Issue by DevelopDaily** [fedimser/quantum_decomp#2]
Your paper is really useful. You mentioned the further decomposition in it. 

> However, two-level matrix can be decomposed into sequence of simpler gates, namely Ry, Rz and R1 gates acting on single qubit and CNOT

Would you please actually implement that? That would be a wonderful feature because that makes all the unitary matrices functional in QASM. Right now, your software is able to produce cirq circuits, which can be converted to QASM  with cirq.Circuit.to_qasm(), but it works only for two qubits.

**Comment by fedimser** [comment]
Hi,
Thank you for yor request.

This library currently can build Cirq circuit for any unitary, however not any such cirquit can be converted to QASM by Cirq. Cirq currently can't convert controlled gate with more than one controls to QASM.

QASM itself is low-level and "multi-controlled gate" isn't part of its spec: https://github.com/Qiskit/openqasm/blob/master/spec/qasm2.rst#language

However, there is an algorithm which decomposes such multi-controlled gate into a sequence of 1-qubit gates, CNOT and CCNOTs: https://cirq.readthedocs.io/en/stable/generated/cirq.decompose_multi_controlled_rotation.html
You can try tthe following:
1. Call qd.matrix_to_cirq_circuit;
2. Iterate through gates in the result, and for all gates which have more than one control, apply cirq.decompose_multi_controlled_rotation
3. Apply cirq.Circuit.to_qasm() to the result.
This, however, will be suboptimal - it will generate more gates than it could. 

I don't intend to continue developing and supporting this library, but if indeed there is no other available open-source Python library capable of converting arbitrary unitary to QASM, I will integrate my algorithm into Cirq, and then improve it so it supports all matrices.

**Comment by DevelopDaily** [comment]
Great. I didn't know `decompose_multi_controlled_rotation` existed.

Thanks.

**Comment by DevelopDaily** [comment]
It seems `cirq.decompose_multi_controlled_rotation` cannot be used to produce a QASM because it returns a list of `cirq.Operation` objects, which lack gate name and argument information. The `cirq.Operation ` does have the correct matrix information, of course. But, the matrix info cannot be directly used to produce a QASM.

Another open source project [OpenQL ](https://github.com/QE-Lab/OpenQL) does have a decomposition module based on [this paper. ](https://repository.tudelft.nl/islandora/object/uuid%3A9c60d13d-4f42-4d8b-bc23-5de92d7b9600)

But, your decomposition strategy is different. So, I do hope you use your algorithm to improve Cirq in the future.

Thanks.

**Comment by rvanasa** [comment]
@DevelopDaily Acknowledging that it's been a while since you posted this issue, I just opened a pull request which makes it possible to generate Qiskit circuits, which you can use to decompose multi-controlled gates for QASM. 

```py
# Random 3-qubit unitary matrix
U = stats.unitary_group.rvs(2 ** 3)

# Generate and decompose circuit
qc = matrix_to_qiskit_circuit(U).decompose()

# Add measurement gates
qc.measure_all()

# Compile QASM string
qasm_string = qc.qasm()
```

**Comment by DevelopDaily** [comment]
Great. Thanks.

Got the idea, though the `previous != qc` will crash. I guess you meant to do 

`while previous is None or previous != qc:`

I didn't verify the correctness of the QASM output, and hope your test cases have covered that.

**Comment by rvanasa** [comment]
The QASM output is correct to the extent that Qiskit implemented it correctly, so there are a few caveats such as `u3(...)` instructions being named `u(...)`, and `u1(...)` being named `p(...)`. Overriding Qiskit's non-standard QASM spec is probably outside of this scope of this library, though. 

That being said, here is a quick-and-dirty way to replace these non-standard gate names:

```py
qasm_string = qc.qasm().replace('\nu(', '\nu3(').replace('\np(', '\nu1(')
```

Also, `previous != qc` works because the first iteration evaluates to `None != qc`, which is true. 

Cheers! :)
